import { useState } from 'react';
import { aiAPI } from '../services/api';
import { formatCurrency } from '../utils/helpers';
import toast from 'react-hot-toast';

export default function ItineraryPage() {
  const [form, setForm] = useState({
    destination: '', numDays: 3, budget: 'moderate', groupSize: 2,
    travelMode: 'train', interests: '', startDate: '',
  });
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await aiAPI.generateItinerary({
        ...form,
        interests: form.interests.split(',').map(s => s.trim()).filter(Boolean),
      });
      setItinerary(res.data);
      toast.success('Itinerary generated by AI!');
    } catch {
      toast.error('Generation failed. Check your Gemini API key.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="section">
        <div className="text-center mb-12">
          <span className="badge-accent mb-4 inline-block">🗓️ AI Itinerary</span>
          <h1 className="section-title mx-auto">AI Itinerary Generator</h1>
          <p className="section-subtitle mx-auto mt-4">Gemini AI creates a personalized day-by-day travel plan for you.</p>
        </div>

        {/* Form */}
        <div className="max-w-xl mx-auto mb-12">
          <div className="card">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="text-sm text-surface-300 mb-1 block">Destination</label>
                <input value={form.destination} onChange={(e) => setForm(f => ({...f, destination: e.target.value}))}
                  placeholder="e.g., Manali" className="input-field" required />
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="text-sm text-surface-300 mb-1 block">Days</label>
                  <input type="number" value={form.numDays} min="1" max="14"
                    onChange={(e) => setForm(f => ({...f, numDays: parseInt(e.target.value)}))} className="input-field" />
                </div>
                <div>
                  <label className="text-sm text-surface-300 mb-1 block">Group</label>
                  <input type="number" value={form.groupSize} min="1"
                    onChange={(e) => setForm(f => ({...f, groupSize: parseInt(e.target.value)}))} className="input-field" />
                </div>
                <div>
                  <label className="text-sm text-surface-300 mb-1 block">Budget</label>
                  <select value={form.budget} onChange={(e) => setForm(f => ({...f, budget: e.target.value}))} className="input-field">
                    <option value="budget">Budget</option>
                    <option value="moderate">Moderate</option>
                    <option value="luxury">Luxury</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="text-sm text-surface-300 mb-1 block">Interests (comma separated)</label>
                <input value={form.interests} onChange={(e) => setForm(f => ({...f, interests: e.target.value}))}
                  placeholder="adventure, food, culture, photography" className="input-field" />
              </div>
              <div>
                <label className="text-sm text-surface-300 mb-1 block">Start Date</label>
                <input type="date" value={form.startDate} onChange={(e) => setForm(f => ({...f, startDate: e.target.value}))} className="input-field" />
              </div>
              <button type="submit" disabled={loading} className="btn-primary w-full !py-3.5">
                {loading ? '🧠 Generating with AI...' : '🧠 Generate Itinerary'}
              </button>
            </form>
          </div>
        </div>

        {/* Itinerary Result */}
        {itinerary && !itinerary.parseError && (
          <div className="space-y-6 animate-fade-up">
            {itinerary.summary && (
              <div className="card bg-primary-500/5 border-primary-500/20">
                <h3 className="font-display font-bold text-xl text-white mb-2">📍 {itinerary.destination}</h3>
                <p className="text-surface-300">{itinerary.summary}</p>
              </div>
            )}

            {itinerary.days?.map((day, i) => (
              <div key={i} className="card-hover">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-gradient-primary rounded-xl flex items-center justify-center text-white font-bold">
                    {day.day}
                  </div>
                  <h3 className="font-display font-semibold text-lg text-white">{day.title}</h3>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                  {['morning', 'afternoon', 'evening'].map(time => day[time] && (
                    <div key={time} className="glass-card p-4">
                      <p className="text-xs text-primary-400 font-semibold uppercase mb-1">{time}</p>
                      <p className="font-medium text-white text-sm">{day[time].activity}</p>
                      <p className="text-xs text-surface-400 mt-1">{day[time].description}</p>
                      <div className="flex justify-between mt-2 text-xs text-surface-500">
                        <span>⏱️ {day[time].duration}</span>
                        <span>{formatCurrency(day[time].estimatedCost || 0)}</span>
                      </div>
                    </div>
                  ))}
                </div>

                {day.meals && (
                  <div className="flex gap-4 text-xs text-surface-400">
                    <span>🍳 {day.meals.breakfast}</span>
                    <span>🍛 {day.meals.lunch}</span>
                    <span>🍽️ {day.meals.dinner}</span>
                  </div>
                )}
                {day.tips && <p className="text-xs text-accent-400 mt-2">💡 {day.tips}</p>}
              </div>
            ))}

            {itinerary.totalEstimatedCost && (
              <div className="card text-center">
                <p className="text-surface-400">Total Estimated Cost</p>
                <p className="text-3xl font-bold text-white">{formatCurrency(itinerary.totalEstimatedCost)}</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
